# -*- coding: utf-8 -*-
"""Clor2grayscale (Q12 - 14)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4qv0LNWbf3-T43KcJANrE8sC4O-1s68
"""

!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.pyplot as plt
import numpy as np
import cv2
def color2grayscale(vector):
    return np.max(vector) * 0.5 + np.min(vector) * 0.5

img_path = "/content/dog.jpeg"
image = cv2.imread(img_path)
img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
gray_image_01 = np.apply_along_axis(color2grayscale, axis=2, arr=img)
plt.imshow(gray_image_01, cmap=plt.get_cmap('gray'))
plt.show()



import matplotlib.pyplot as plt
import numpy as np
import cv2
def color2grayscale(vector):
    return np.max(vector) * 0.5 + np.min(vector) * 0.5

img_path = "/content/dog.jpeg"
image = cv2.imread(img_path)
img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
gray_image_01 = np.apply_along_axis(color2grayscale, axis=2, arr=img)
gray_image_01 [0, 0]



import matplotlib.pyplot as plt
import numpy as np
import cv2

def color2grayscale (vector):
    return np.sum(vector)/3
image = cv2.imread("/content/dog.jpeg")
img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
gray_image_02 = np.apply_along_axis(color2grayscale, axis = 2, arr = img)
gray_image_02 [0, 0]

import matplotlib.pyplot as plt
import numpy as np
def color2grayscale (vector):
    return vector[0]*0.21 + vector[1]*0.72 + vector[2]*0.07

gray_image_03 = np.apply_along_axis(color2grayscale, axis = 2, arr = img)
gray_image_03 [0, 0]