# -*- coding: utf-8 -*-
"""Tabular Data Analysis (Q15-21)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vT-OiAB7w4L6LXyHAujdLbQ5fzOpRJZc
"""

!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq



import pandas as pd

# Đọc tệp CSV vào pandas DataFrame
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()

"""Câu hỏi 15: Lấy giá trị lớn nhất và chỉ mục tương ứng của nó trên cột Sales:"""

import numpy as np
sales_data = data[:, 3]
sales_max = np.max(sales_data)

sales_idx = np.argmax(sales_data)
sales_max, sales_idx

"""Câu hỏi 16: Giá trị trung bình của cột TV là:"""

tv_mean = data[:, 0].mean()
tv_mean

"""Câu hỏi 17: Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20 là:

Câu hỏi 18: Tính giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng
trên cột Sales lớn hơn hoặc bằng 15:
"""

sale_cond = data[:, 3] >= 15.0
radio_data = data[:, 1]

radio_cond = radio_data * sale_cond
radio_mean = np.sum(radio_cond) / np.sum(sale_cond)

radio_mean

"""Câu hỏi 19: Tính tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn
giá trị trung bình của cột Newspaper:
"""

newspaper_data = data[:, 2]
newspaper_mean = newspaper_data.mean()

newspaper_cond = newspaper_data > newspaper_mean
sales_data = data[:, 3]

sales_cond = sales_data * newspaper_cond
sales_sum = np.sum(sales_cond)

sales_sum

"""Câu hỏi 20: Gọi giá trị trung bình của cột Sales là A. Tạo ra mảng mới scores chứa các
giá trị Good, Average và Bad sao cho: nếu giá trị hiện tại > A => giá trị trong mảng mới
là Good, < A thì sẽ là Bad và = A sẽ là Average. Sau đó in ra kết quả scores[7:10]
"""

sales_data = data[:, 3]
sales_mean = sales_data.mean()
score_sales = np.where(
    sales_data < sales_mean,
    "Bad",
    np.where(sales_data > sales_mean, "Good", "Average")
)
score_sales [7:10]

"""Câu hỏi 21: Gọi giá trị trên cột Sales gần nhất với giá trị trung bình cũng chính cột
Sales là A. Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: nếu
giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là
Average. Sau đó in ra kết quả scores[7:10]
"""

sales_data = data[:, 3]
sales_mean = sales_data.mean()
sub_mean = sales_data - sales_mean
sub_abs = abs(sales_data - sales_mean)
average_idx = np.argmin(sub_abs)
sales_average = sales_data[average_idx]
score_sales = np.where(
    sales_data < sales_mean,
    "Bad",
    np.where(sales_data > sales_average, "Good", "Average")
)
score_sales [7:10]